### ISSUE TITLE
Need image update for timing delays

### ISSUE THREAD

**Issue by TonyGiorgio** [BitcoinDevShop/lightning-privacy-research#17]
![Screenshot from 2022-11-30 14-50-39](https://user-images.githubusercontent.com/101225832/204905354-62668b1c-0c18-4582-a8e3-a51fe9e36ac4.png)

These two images show the same timings. I believe the bottom one needs to show the receiver holding the payment for 3x the time (I guess 1500ms instead of 500ms), and then that also increases the the delay between the bad guy and router (2000ms instead of 1000ms).

**Comment by futurepaul** [comment]
how's this?

<img width="648" alt="Screen Shot 2022-11-30 at 3 01 29 PM" src="https://user-images.githubusercontent.com/543668/204907178-79a37c79-11e1-4413-86f3-7f80b5e6c9c0.png">

**Comment by TonyGiorgio** [comment]
Swap the 1500ms with the 500ms on the right
